### ISSUE TITLE
Какую цену передавать при покупке по рынку

### ISSUE THREAD

**Issue by Freeongoo** [RussianInvestments/invest-api-java-sdk#15]
не понял суть передачи цены если при вызове getInvestApi().getOrdersService().postOrderSync() и выбрать тип OrderType.ORDER_TYPE_MARKET, то передача цены всеравно обязательна. Зачем передавать цену?

**Comment by sradykoff** [comment]
да, в postOrderSync предусмотрена передача цены для лимитных заявок. в случае ORDER_TYPE_MARKET  получается не очень правильно, как вариант - в цену можно передавать Quotation.getDefaultInstance()
